apiVersion: v1
data:
  mysqld.cnf: |-
    [mysqld]
    skip-host-cache
    skip-name-resolve

    #
    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License, version 2.0, for more details.
    #
    # You should have received a copy of the GNU General Public License
    # along with this program; if not, write to the Free Software
    # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA

    #
    # The MySQL  Client configuration file.
    #
    # For explanations see
    # http://dev.mysql.com/doc/mysql/en/server-system-variables.html

    [mysql]
    
kind: ConfigMap
metadata:
  name: mysql-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-1
  labels:
    app: mysql-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-1
  template:
    metadata:
      labels:
        app: mysql-1
    spec:
      volumes:
      - name: mysql-1-volume
        persistentVolumeClaim:
          claimName: pvc-nfs-mysql-1
      - name: config-volume
        configMap:
          name: mysql-config
      containers:
        - image: mysql
          name: mysql-1
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: '123456'
          resources:
           limits:
             memory: 512Mi
             cpu: 500m
           requests:
             memory: 50Mi
             cpu: 50m
          volumeMounts:
            - name: mysql-1-volume
              mountPath: /var/lib/mysql
            - name: config-volume
              mountPath: "/etc/mysql/mysql.conf.d/"
---
kind: Service
apiVersion: v1
metadata:
  name: mysql-1-service
spec:
  selector:
    app: mysql-1
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      nodePort: 32306
  type: NodePort
---
